In [1]:
import numpy as np
import pandas as pd

#### Creating Data Frames
DataFrames are 2-dimensional labeled data structures in Pandas. They can be thought of as a collection of Series objects that share the same index. We can create a DataFrame from a variety of data sources, including lists, dictionaries, and NumPy arrays.

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 34, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Salary' : [70000, 80000, 90000, 100000]
}

In [3]:
df_dic = pd.DataFrame(data)
df_dic

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   34      Chicago   90000
3    David   40      Houston  100000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df_list = pd.DataFrame(data_list) # Creating DataFrame from list of lists without column names
print(df_list, "\n")

# Now giving names to columns while creating DataFrame
df_list_named = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print(df_list_named)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and Indexing of Columns

In [5]:
my_df = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])

In [6]:
# Calling separate columns using column names
my_df['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

**Selecting a Column**

In [7]:
my_df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

**Selecting Multiple columns**

In [8]:
# Selecting multiple columns
my_df[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating New Columns**

In [9]:
my_df['Designation'] = ['Engineer', 'Designer', 'Manager', 'Director']

In [10]:
my_df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000    Designer
2  Peter   29    Berlin   62000     Manager
3  Linda   42    London   85000    Director

**Deleting a Column**

In [11]:
my_df.drop('Designation', axis = 1) # Using Drop() this will not be removed from original dataframe so for this we have to use inplace function

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
print(my_df)
my_df.drop('Designation', axis = 1, inplace = True) # Using inplace = True will remove the column from original dataframe
print(my_df)

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000    Designer
2  Peter   29    Berlin   62000     Manager
3  Linda   42    London   85000    Director
    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
my_df.drop(['Age', 'City'], axis = 1) # Dropping multiple columns

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [15]:
my_df.drop(3, axis = 0) # Dropping a row using index

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

**Selecting a Row**

In [16]:
my_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
my_df.loc[0] # Accessing row using loc
print(my_df.loc[0])

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [19]:
my_df.iloc[0] # Accessing row using iloc

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [22]:
print(my_df)
my_df.loc[[0,1]][['City', 'Salary']] # Accessing multiple rows and columns using loc

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

       City  Salary
0  New York   65000
1     Paris   70000

In [23]:
my_df.loc[[2,3]][['Name', 'Age']] # Accessing multiple rows and columns using loc

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection in DataFrames**

In [24]:
my_df[my_df['Age'] > 30] # Filtering rows based on condition

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [26]:
my_df[(my_df['Age'] > 30) & (my_df['City'] == 'Paris')] # Filtering rows based on multiple conditions

   Name  Age   City  Salary
1  Anna   34  Paris   70000