In [2]:
import numpy as np
import pandas as pd

#### Creating Data Frames
DataFrames are 2-dimensional labeled data structures in Pandas. They can be thought of as a collection of Series objects that share the same index. We can create a DataFrame from a variety of data sources, including lists, dictionaries, and NumPy arrays.

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 34, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Salary' : [70000, 80000, 90000, 100000]
}

In [4]:
df_dic = pd.DataFrame(data)
df_dic

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   34      Chicago   90000
3    David   40      Houston  100000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df_list = pd.DataFrame(data_list) # Creating DataFrame from list of lists without column names
print(df_list, "\n")

# Now giving names to columns while creating DataFrame
df_list_named = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print(df_list_named)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and Indexing of Columns

In [12]:
my_df = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])

In [13]:
# Calling separate columns using column names
my_df['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

**Selecting a Column**

In [14]:
my_df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

**Selecting Multiple columns**

In [15]:
# Selecting multiple columns
my_df[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating New Columns**

In [16]:
my_df['Designation'] = ['Engineer', 'Designer', 'Manager', 'Director']

In [17]:
my_df

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000    Designer
2  Peter   29    Berlin   62000     Manager
3  Linda   42    London   85000    Director

**Deleting a Column**

In [ ]:
my_df.drop('Designation', axis = 1) # Using Drop() this will not be removed from original dataframe so for this we have to use inplace function

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
print(my_df)
my_df.drop('Designation', axis = 1, inplace = True) # Using inplace = True will remove the column from original dataframe
print(my_df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

KeyError: "['Designation'] not found in axis"