In [1]:
import numpy as np
import pandas as pd

## Missing Data

**1. Finding Missing Data**

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
my_df = pd.DataFrame(data)

In [3]:
my_df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [6]:
print(my_df.isna(), "\n") # Check for missing values
print(my_df.isna().sum()) # Count missing values in each column

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

A    1
B    0
C    2
D    3
dtype: int64

In [9]:
my_df.isna().any() # Check if any missing values exist in the DataFrame

A     True
B    False
C     True
D     True
dtype: bool

**2. Removing Missing Data**

In [12]:
my_df.dropna() # Drop rows with missing values

     A  B    C    D
0  1.0  1  1.0  1.0

In [13]:
my_df.dropna(thresh = 3) # Drop rows that have less than 3 non-NA values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**3. Filling Missing Values**

In [14]:
my_df.fillna(0) # Fill missing values with 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [15]:
values = {'A': 100, 'B' : 200, 'C': 300, 'D': 400}
my_df.fillna(value = values) # Fill missing values with different values for each column

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [16]:
my_df.fillna(my_df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0